### ISSUE TITLE
Form!

### ISSUE THREAD

**Issue by AsalaKM** [FACG6/3AF#24]
#### Also, I really don't like how you use the `<br>`
https://github.com/FACG6/3AF/blob/e5f8d1c2dc709f2bd026fad70e068d902979f430/index.html#L134-L157

**Comment by ali-7** [comment]
you can use 

```css
.container input { 
      display:block;
 }
```
